// Comprehensive fallback data for GSoC 2026 organizations
// This data is used when the external API is unavailable

export const gsoc2026Organizations = [
  {
    name: "Python Software Foundation",
    description: "Python is a programming language that lets you work quickly and integrate systems more effectively.",
    technologies: ["Python", "Django", "Flask", "NumPy", "Pandas", "Pytest"],
    category: "Programming languages",
    url: "https://www.python.org/",
    ideas_list: "https://python-gsoc.org/",
    topics: ["web", "data-science", "machine-learning", "automation", "testing"],
    year: 2026,
  },
  {
    name: "Mozilla",
    description: "Mozilla is the not-for-profit behind Firefox, fighting for a healthy internet for all.",
    technologies: ["JavaScript", "Rust", "C++", "Python", "WebAssembly"],
    category: "Web",
    url: "https://www.mozilla.org/",
    ideas_list: "https://wiki.mozilla.org/Community:SummerOfCode",
    topics: ["browser", "privacy", "security", "web-standards"],
    year: 2026,
  },
  {
    name: "TensorFlow",
    description: "An end-to-end open source machine learning platform for everyone.",
    technologies: ["Python", "C++", "TensorFlow", "Keras", "JAX"],
    category: "Artificial Intelligence",
    url: "https://www.tensorflow.org/",
    ideas_list: "https://github.com/tensorflow/community/tree/master/sigs",
    topics: ["ai", "machine-learning", "deep-learning", "neural-networks"],
    year: 2026,
  },
  {
    name: "Apache Software Foundation",
    description: "The Apache Software Foundation provides support for the Apache community of open-source software projects.",
    technologies: ["Java", "Scala", "Python", "Go", "C++"],
    category: "Infrastructure and cloud",
    url: "https://www.apache.org/",
    ideas_list: "https://community.apache.org/gsoc.html",
    topics: ["big-data", "cloud", "web-server", "databases"],
    year: 2026,
  },
  {
    name: "Cloud Native Computing Foundation (CNCF)",
    description: "Building sustainable ecosystems for cloud native software.",
    technologies: ["Go", "Kubernetes", "Docker", "Rust", "Python"],
    category: "Infrastructure and cloud",
    url: "https://www.cncf.io/",
    ideas_list: "https://github.com/cncf/mentoring",
    topics: ["kubernetes", "containers", "cloud-native", "devops"],
    year: 2026,
  },
  {
    name: "PostgreSQL",
    description: "The world's most advanced open source relational database.",
    technologies: ["C", "SQL", "PostgreSQL", "PL/pgSQL"],
    category: "Data",
    url: "https://www.postgresql.org/",
    ideas_list: "https://wiki.postgresql.org/wiki/GSoC",
    topics: ["database", "sql", "data-storage", "backend"],
    year: 2026,
  },
  {
    name: "Git",
    description: "Git is a free and open source distributed version control system.",
    technologies: ["C", "Shell", "Perl", "Python"],
    category: "Development tools",
    url: "https://git-scm.com/",
    ideas_list: "https://git.github.io/SoC-2024-Ideas/",
    topics: ["version-control", "devtools", "collaboration"],
    year: 2026,
  },
  {
    name: "Kubernetes",
    description: "Production-Grade Container Orchestration.",
    technologies: ["Go", "Kubernetes", "Docker", "YAML"],
    category: "Infrastructure and cloud",
    url: "https://kubernetes.io/",
    ideas_list: "https://github.com/kubernetes/community/tree/master/mentoring",
    topics: ["containers", "orchestration", "cloud", "devops"],
    year: 2026,
  },
  {
    name: "NumPy",
    description: "The fundamental package for scientific computing with Python.",
    technologies: ["Python", "C", "NumPy", "Cython"],
    category: "Science and medicine",
    url: "https://numpy.org/",
    ideas_list: "https://github.com/numpy/numpy/wiki/GSoC-2024-project-ideas",
    topics: ["data-science", "scientific-computing", "mathematics"],
    year: 2026,
  },
  {
    name: "Django Software Foundation",
    description: "The web framework for perfectionists with deadlines.",
    technologies: ["Python", "Django", "JavaScript", "PostgreSQL", "HTML", "CSS"],
    category: "Web",
    url: "https://www.djangoproject.com/",
    ideas_list: "https://code.djangoproject.com/wiki/SummerOfCode2024",
    topics: ["web", "backend", "framework", "python"],
    year: 2026,
  },
  {
    name: "Rust Foundation",
    description: "A language empowering everyone to build reliable and efficient software.",
    technologies: ["Rust", "LLVM", "C++"],
    category: "Programming languages",
    url: "https://www.rust-lang.org/",
    ideas_list: "https://github.com/rust-lang/google-summer-of-code",
    topics: ["systems-programming", "performance", "safety", "memory-safety"],
    year: 2026,
  },
  {
    name: "React",
    description: "A JavaScript library for building user interfaces.",
    technologies: ["JavaScript", "TypeScript", "React", "React Native"],
    category: "Web",
    url: "https://react.dev/",
    ideas_list: "https://github.com/reactjs/rfcs",
    topics: ["frontend", "ui", "mobile", "web"],
    year: 2026,
  },
  {
    name: "Linux Foundation",
    description: "Supporting the creation of open source software through financial and intellectual resources.",
    technologies: ["C", "C++", "Linux", "Kernel", "Assembly"],
    category: "Operating systems",
    url: "https://www.linuxfoundation.org/",
    ideas_list: "https://wiki.linuxfoundation.org/gsoc",
    topics: ["linux", "kernel", "operating-systems", "drivers"],
    year: 2026,
  },
  {
    name: "Node.js Foundation",
    description: "Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine.",
    technologies: ["JavaScript", "Node.js", "C++", "V8"],
    category: "Programming languages",
    url: "https://nodejs.org/",
    ideas_list: "https://github.com/nodejs/node/blob/main/doc/contributing/",
    topics: ["javascript", "runtime", "backend", "server"],
    year: 2026,
  },
  {
    name: "OpenCV",
    description: "Open Source Computer Vision Library.",
    technologies: ["C++", "Python", "OpenCV", "CUDA"],
    category: "Artificial Intelligence",
    url: "https://opencv.org/",
    ideas_list: "https://github.com/opencv/opencv/wiki/GSoC",
    topics: ["computer-vision", "image-processing", "ai", "ml"],
    year: 2026,
  },
  {
    name: "Jenkins",
    description: "The leading open source automation server.",
    technologies: ["Java", "Groovy", "Jenkins", "Docker"],
    category: "Development tools",
    url: "https://www.jenkins.io/",
    ideas_list: "https://www.jenkins.io/projects/gsoc/",
    topics: ["ci-cd", "automation", "devops", "testing"],
    year: 2026,
  },
  {
    name: "Wikimedia Foundation",
    description: "The nonprofit that hosts Wikipedia and other free knowledge projects.",
    technologies: ["PHP", "JavaScript", "MediaWiki", "MySQL", "Redis"],
    category: "Social and communication",
    url: "https://www.wikimedia.org/",
    ideas_list: "https://www.mediawiki.org/wiki/Google_Summer_of_Code",
    topics: ["wiki", "knowledge", "web", "collaboration"],
    year: 2026,
  },
  {
    name: "GNOME Foundation",
    description: "GNOME is a desktop environment for Linux and Unix-like operating systems.",
    technologies: ["C", "Vala", "GTK", "JavaScript", "Python"],
    category: "End user applications",
    url: "https://www.gnome.org/",
    ideas_list: "https://wiki.gnome.org/Outreach/SummerOfCode",
    topics: ["desktop", "linux", "ui", "gtk"],
    year: 2026,
  },
  {
    name: "KDE Community",
    description: "An international free software community that develops free and open-source software.",
    technologies: ["C++", "Qt", "QML", "Python"],
    category: "End user applications",
    url: "https://kde.org/",
    ideas_list: "https://community.kde.org/GSoC",
    topics: ["desktop", "linux", "qt", "applications"],
    year: 2026,
  },
  {
    name: "MariaDB Foundation",
    description: "MariaDB Server is one of the most popular open source relational databases.",
    technologies: ["C", "C++", "SQL", "MariaDB"],
    category: "Data",
    url: "https://mariadb.org/",
    ideas_list: "https://mariadb.org/get-involved/gsoc/",
    topics: ["database", "sql", "mysql", "backend"],
    year: 2026,
  },
]
